data=[    
{
brand:"Puma",
type:"Ws AOP Tee",
imgsrc:"./mybag/women t-shirts/wtshirts.jpg",
price:1000,
op:1999,
discount:"(50% off)",
bbs:"BBS Price 750",
},
{
    brand:"LEVIS",
    type:"Crew-Neck T-shirt with Brand Print",
    imgsrc:"./mybag/women t-shirts/wtshirts1.jpg",
    price:635,
    op:1199,
    discount:"(47% off)",
    bbs:"BBS Price 576",
 },
 {
    brand:"Teamspirit",
    type:"Colourblock Striped Round Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts2.jpg",
    price:336,
    op:699,
    discount:"(52% off)",
    bbs:"BBS Price 210",
 },
 {
    brand:"Teamspirit",
    type:"Printed T-shirt with Full Sleeves",
    imgsrc:"./mybag/women t-shirts/wtshirts3.jpg",
    price:384,
    op:799,
    discount:"(52% off)",
    bbs:"BBS Price 240",
 },
 {
    brand:"FIG",
    type:"Ribbed Round-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts4.jpg",
    price:424,
    op:499,
    discount:"(15% off)",
    bbs:"BBS Price 399",
 },
 {
    brand:"Calvin Klein Jeans",
    type:"Crew-Neck T-shirt with Embroidered Brand Text",
    imgsrc:"./mybag/women t-shirts/wtshirts5.jpg",
    price:1749,
    op:2499,
    discount:"(30% off)",
    bbs:"BBS Price 1574",
 },
 {
    brand:"Teamspirit",
    type:"Typographic Print Crew-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts6.jpg",
    price:699,
    op:999,
    discount:"(30% off)",
    bbs:"BBS Price 629",
 },

 {
    brand:"TOMMY HILFIGER",
    type:"Organic Cotton Crew-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts7.jpg",
    price:1199,
    op:1999,
    discount:"(40% off)",
    bbs:"BBS Price 1099",
 },
 {
    brand:"TOMMY HILFIGER",
    type:"Brand Logo Embroidered Crew-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts8.jpg",
    price:1299,
    op: 1999,
    discount:"(35% off)",
    bbs:"BBS Price 1199",
 },
 {
    brand:"TOMMY HILFIGER",
    type:"Crew-Neck T-shirt with Brand Embroidery",
    imgsrc:"./mybag/women t-shirts/wtshirts9.jpg",
    price:1039,
    op: 1599,
    discount:"(35% off)",
    bbs:"BBS Price 959",
 },
 {
    brand:"TOMMY HILFIGER",
    type:"Brand Print Crew-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts10.jpg",
    price:1585,
    op:2599,
    discount:"(39% off)",
    bbs:"BBS Price 1429",
 },
 {
    brand:"TOMMY HILFIGER",
    type:"Brand Print T-shirt with Drop Shoulders",
    imgsrc:"./mybag/women t-shirts/wtshirts11.jpg",
    price:1043,
    op:1799,
    discount:"(42% off)",
    bbs:"BBS Price 900",
 },
 {
    brand:"TOMMY HILFIGER",
    type:"Printed Crew-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts12.jpg",
    price: 1007,
    op:1599,
    discount:"(37% off)",
    bbs:"BBS Price 879",
 },
 {
    brand:"Puma",
    type:"Brand Print Crew-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts13.jpg",
    price:1199,
    op:1999,
    discount:"(40% off)",
    bbs:"BBS Price 899",
 },
 {
    brand:"TOMMY HILFIGER",
    type:"Logo Print Crew-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts14.jpg",
    price:1349,
    op:1799,
    discount:"(25% off)",
    bbs:"BBS Price 1223",
 },
 {
    brand:"TOMMY HILFIGER",
    type:"Brand Print Crew-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts15.jpg",
    price:1689,
    op:2599,
    discount:"(35% off)",
    bbs:"BBS Price 1559",
 },
 {
    brand:"ARMANI EXCHANGE",
    type:"Logo Print Slim Fit Crew-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts16.jpg",
    price: 4199,
    op:5999,
    discount:"(30% off)",
    bbs:"BBS Price 3419",
 },
 {
    brand:"Puma",
    type:"Brand Icon Print Crew-Neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts17.jpg",
    price:520,
    op:1299,
    discount:"(60% off)",
    bbs:"BBS Price 442",
 },
 {
    brand:"TOMMY HILFIGER",
    type:"Cotton V-neck T-shirt",
    imgsrc:"./mybag/women t-shirts/wtshirts18.jpg",
    price:927,
    op:1599,
    discount:"(42% off)",
    bbs:"BBS Price 800",
 },
 {
    brand:"TOMMY HILFIGER",
    type:"Round-Neck T-shirt with Full Sleeves",
    imgsrc:"./mybag/women t-shirts/wtshirts19.jpg",
    price:1097,
    op:1799,
    discount:"(39% off)",
    bbs:"BBS Price 989",
 },
]